# Generated by Django 4.2 on 2023-04-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dbapp',
            new_name='Artifact',
        ),
    ]
