# Generated by Django 4.2 on 2023-04-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_rename_dbapp_artifact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='text',
        ),
        migrations.AddField(
            model_name='artifact',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='Level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
